<<<<<<< HEAD
[theme]
base="light"
primaryColor="#262730"
secondaryColor="#E83945"
textColor="#31333F"
backgroundColor="#F5F5DC"

[server]
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false

[ui]
hideMenu = true
hideFooter = true
=======
[theme]
base="light"
primaryColor="#262730"
secondaryColor="#E83945"
textColor="#31333F"
backgroundColor="#F5F5DC"

[server]
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false

[ui]
hideMenu = true
hideFooter = true
>>>>>>> 8c3ba40e0b079bd3971fd6fc39758bc8ed86bf80
