[theme]
base="light"
[theme]
base="light"  # o "dark" si prefieres

[server]
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false

[ui]
hideMenu = true
hideFooter = true
primaryColor="#262730"
secondaryColor="#E83945"
textColor="#31333F"
backgroundColor="#F5F5DC"
